### ISSUE TITLE
Požádat o GitHub for non-profits

### ISSUE THREAD

**Issue by spacekpe** [InstruktoriBrno/citron#1]
https://github.com/nonprofit

**Comment by spacekpe** [comment]
Žádost odeslána.

**Comment by mukrop** [comment]
Parada, dik.
For future reference: Ak ziskame privatne repa, navrhnut Tmou premigrovat repo pod nas.

**Comment by spacekpe** [comment]
Máme to, účet InstruktoriBrno byl povýšen.

@miiila Prosím zvažte s týmem TMOU rep pod organizaci InstruktoriBrno, ať máme všechno na jednom místě. Díky!
