### ISSUE TITLE
Zvážit, jestli nesnížit TTL na *.instruktori.cz

### ISSUE THREAD

**Issue by kuldazbraslav** [InstruktoriBrno/citron#27]
Momentálně máme TTL na 48 hodin a zároveň CNAME ukazuje na admiral.toad.cz, což znamená, že v případě výpadku serveru nejsme schopni ho rychle postavit jinde. Kratší TTL by nám usnadnilo reakci v případě problémů.

**Comment by spacekpe** [comment]
Ahoj,

je k diskusi, čeho se bojíme víc - výpadku serveru nebo potíží s DNS?

Asi spíš toho serveru, jelikož tam není žádná redundance... TTL co se dala jsem snížil na hodinu, ale FORPSI web rozhraní pro DNS mi nedovolí změnit TTL u záznamů s víc hodnotami - ty jsem nechal jak byly.
