### ISSUE TITLE
Zkusit zmigrovat maximum statických webů na github pages

### ISSUE THREAD

**Issue by kuldazbraslav** [InstruktoriBrno/citron#31]
* jen instruktori.cz
* zkusit, jak to bude bolet
* zkontrolovat citlivé údaje
* na veřejná repa
* otestovat přístup
* změnit DNS
* zarchivovat (abychom nedostávali security hlášky)

**Comment by kuldazbraslav** [comment]
Zkusil jsem zmigrovat babylon.instruktori.cz (akce z roku 2009) a zabralo mi to asi 15 minut včetně konverze kódování a úpravy kódování v `<meta>` hlavičkách.

1. Vytvořit veřejné repo babylon-web
2. Zkopírovat si /var/www/babylon.instruktori.cz k sobě do home
```
cp -R /var/www/babylon.instruktori.cz/ ~
```
3. `git init`
4. `git commit`
5. Aktivovat github pages s doménou babylon.instruktori.cz
6. Počkat, až naběhnou
7. Přesměrovat DNS
8. zarchivovat repo
9. deaktivovat site na apachi
```
a2dissite babylon.instruktori.cz
a2dissite babylon.instruktori.cz-le-ssl
systemctl reload apache2
```

**Comment by kuldazbraslav** [comment]
Hodlám ještě zmigrovat následující weby, vidíte tam nějaký, který není statický? @mukrop @spacekpe 

```
funfactory
intime
island
klap10
klap
kytky
labyrint13
labyrint
louskac
muzvesmiru
naprijmu
obzory
omuzichazenach
outdoor
outdoorlight
outdoorvikend
perzona
pokr
pribehy
promethea
sepot
setkani11
souhvezdar
spirithorse
spl2009
spl2010
stoleti
troja
trojjedina
verbovani
vikingove
vjinemrytmu
vodo
vvh
vydra
zdravevztahy
zimni13
```

**Comment by mukrop** [comment]
Videl som tam len ten kraz a kurs, ale tie uz si zo zoznamu vyhodil.

**Comment by kuldazbraslav** [comment]
Tak zmigrováno asi 45 webů, na apachi zůstává už jen 30 domén pod instruktori.cz, z čehož část jsou jen přesměrování nebo weby s databází. Část statických jsou relativně nové věci, kde bych se ještě na migraci domluvil s autory.
