### ISSUE TITLE
Zalozit IS Brno MojeID

### ISSUE THREAD

**Issue by mukrop** [InstruktoriBrno/citron#32]

**Comment by kuldazbraslav** [comment]
Tohle je asi hotove, coz?

**Comment by mukrop** [comment]
No, ono "zalozit" ma viacero krokov :-P. Uz mam aj overenu postovu adresu, ale este to chce validaciu pravnickej osoby, ktoru mam dohodnutu s Alcou. Takze este prosim nechat.

**Comment by mukrop** [comment]
Vsetko hotovo :-).
