### ISSUE TITLE
dotisk fondu: rozsypaná stránka

### ISSUE THREAD

**Issue by spacekpe** [InstruktoriBrno/citron#38]
Zdar,

stránka https://www.instruktori.cz/fondher/dotisk-fond-1/ se mi zobrazuje jako jedna dlouhá nudle s šířkou textu 1 znak.

**Comment by spacekpe** [comment]
Screenshot:
![image](https://user-images.githubusercontent.com/2099568/86832103-4214d180-c087-11ea-95ea-c2f517cdf790.png)

**Comment by mukrop** [comment]
Hm, u mna je vsetko v poriadku, screenshot nizsie (plus vidim, ze tebe sa tam nezobrazuje obrazok). OS? Browser + verzia? Pripadne otvor nejake developer tools a mrkni, ktory div to tlaci na uzko.

![dotisk](https://user-images.githubusercontent.com/1871676/86891698-9065b700-c0ff-11ea-8818-d97e322680f9.png)

**Comment by spacekpe** [comment]
Záhada, v čistém profilu Firefoxu mi to jede, ale v mojem "standardním" profilu to nejede. Čučím do toho a nevidím nic zjevného, prostě "něco" způsobí, že <p> tag má nulovou šířku a nevyznám se v tom co. Každopádně zavírám, když je to úchylárna v mojem profilu. Pardon, měl jsem to otestovat rovnou!
