### ISSUE TITLE
Konsolidovat tímové disky

### ISSUE THREAD

**Issue by mukrop** [InstruktoriBrno/citron#4]
Vytvořit konto, které bude vlastnit týmové disky akcí. (`teamdrives@instruktori.cz`?)

**Comment by spacekpe** [comment]
Proč ne `gadmin`? Nevidím smysl v tom mít to pod zvláštním účtem.

**Comment by mukrop** [comment]
Kludne `gadmin`. Myslienka bola, aby bolo od pohladu jasne, na co to konto je (ale ak bude `gadin na skoro vsetko, tak je to OK`).

**Comment by mukrop** [comment]
Hotovo.
